# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ForestAnalysisPlugin
                                 A QGIS plugin
 Plugin for forest spatial analysis in QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-05-21
        copyright            : (C) 2026 by NIKOLETTA
        email                : anagnostakinikol@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ForestAnalysisPlugin class from file ForestAnalysisPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .forest_analysis_plugin import ForestAnalysisPlugin
    return ForestAnalysisPlugin(iface)
